### PR TITLE
add scripts for batch releasing charms

### PR DESCRIPTION
**Pull request by ca-scribner**
Adds workflow_dispatcher.py and create_release_workflow_dispatch_manifest.py which together make it easier to release multiple charms from one channel to another at once.  See the included README.md for usage instructions

NOTE:
* this PR depends on additional features [added to chisme](https://github.com/canonical/charmed-kubeflow-chisme/pull/27).  At the moment, you must have them locally and edit the requirements.txt file to reference your local copy

Test instructions:
* get a local version of the above chisme PR and add to your requirements.txt file, as mentioned above
* use `tox -e test_batch_release_charms`

Todo before merging:
* [x] [this chisme PR](https://github.com/canonical/charmed-kubeflow-chisme/pull/27) must be merged and released
* [x] requirements.txt in this current PR must be updated to use chisme from pypi
* [ ] squash the debugging commits out of this (or squash merge)

### CODE REVIEW

**Comment by ca-scribner** [comment]
Still fixing up the linting errors, but otherwise it is g2g

**Comment by ca-scribner** [comment]
Not sure why linting is failing.  The flake8 settings in pyproject.toml set a max line width of 99, not 79.  Works locally, but fails here

**Review by i-chvets — DISMISSED** [review]
Approved.
NOTE: May be add notes on how to configure/setup dev/test environment and how to execute tests.

**Comment by ca-scribner** [comment]
Yeah great point, that was not clear

**Review by i-chvets — DISMISSED** [review]
Approved.

**Comment by ca-scribner** [comment]
Added tests for the batch release scripts to the general `on pull_request` CI.  This CI will fail until we get [this chisme PR](https://github.com/canonical/charmed-kubeflow-chisme/pull/27) merged and update the requirements.txt file here

**Review by i-chvets — DISMISSED** [review]
Approved.

**Review by i-chvets — APPROVED** [review]
Approve.

**Pull request merged**
